### ISSUE TITLE
TypeError: unhashable type: 'c4d.BaseObject' raised when importing .omni file

### ISSUE THREAD

**Issue by EnderElement** [Stellaxis/omniscient-cinema4d#1]
This error occurs when attempting to import a .omni file using the importer or dragging it into the scene.
Tested in Cinema 4D versions R26.107 and R2023.1.3 with identical results.

> INFO:OmniscientImporter:Selected .omni file: C:\Users\Mark\Downloads\IMG_181218028_10May\IMG_181218028.omni
> INFO:OmniscientImporter:Parsed .omni data.
> ERROR:OmniscientImporter:An error occurred while processing the .omni file:
> Traceback (most recent call last):
>   File "C:\Program Files\Maxon Cinema 4D R26\plugins\OmniscientImporter\lib\OmniscientImporter.py", line 202, in import_omni_file
>     process_import(doc, obj_path, "Scan_Omni")
>   File "C:\Program Files\Maxon Cinema 4D R26\plugins\OmniscientImporter\lib\OmniscientImporter.py", line 50, in process_import
>     objects_before_import = set(doc.GetObjects())
> TypeError: unhashable type: 'c4d.BaseObject'

However, the importer is able to successfully create a material with the background footage, create a C4D background object, and apply the material to it.

Files exported in the Omniscient app version 1.15.1 on the iPad pro 3rd gen (16.4.1) with the C4D option selected only.
![image](https://github.com/Stellaxis/omniscient-cinema4d/assets/29475587/9c2be933-6bc3-4845-9628-db1cf9818527)

**Comment by Stellaxis** [comment]
Hi @EnderElement, thank you for flagging this issue!

After investigating, based on this[ release note](https://support.maxon.net/hc/en-us/articles/8192911952796-Cinema-4D-2023-2-0-March-29-2023), Maxon updated the  Python version used by Cinema 4D from 3.9 to 3.10.8, which seems to be the cause of the issue. This change occurred in Cinema 4D 2023.2.0, coincidentally the oldest version we tested the plugin with, which is why we didn't experience the issue you're facing.

I just tried a fix below; please let me know if it works:

[OmniscientImporter.zip](https://github.com/Stellaxis/omniscient-cinema4d/files/15272993/OmniscientImporter.zip)

**Comment by EnderElement** [comment]
Ah that change would make sense.
The fix for both my C4D versions worked incredibly well.
Thank you for your time!

**Comment by Stellaxis** [comment]
Thanks @EnderElement for confirming that it fixes the issue! Enjoy the app :)
